# Generated by Django 3.1.3 on 2020-11-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fammunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='num',
        ),
    ]
