# Generated by Django 3.1.3 on 2020-12-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fammunity', '0002_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
